import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";
import Hero from "@/components/layout/Hero";
import PhotoCardsSection from "@/components/layout/PhotoCards";
import StoryPost from "@/components/layout/StoryPost";
import { ImageWithSkeleton } from "@/components/molecule/ImageWithSkeleton";
import { faker } from "@faker-js/faker";
import ArrowRight from "@/icons/ArrowRight";
import Link from "next/link";
import ScrollToTop from "@/components/layout/ScrollToTop";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

// this acts as a parent for all of the other pages
export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<ScrollToTop></ScrollToTop>
				<div className="flex flex-col gap-10 min-h-screen w-screen">
					{/* this is to wrap not full frame */}
					<div className="ml-4 mr-4 flex flex-col gap-2 sm:ml-20 sm:mr-20 sm:gap-10 grow">
						<Header></Header>
						{children}
					</div>
					<Footer></Footer>
				</div>
			</body>
		</html>
	);
}
