import type { Metadata } from "next";
import {
	Fleur_De_Leah,
	Geist,
	Geist_Mono,
	Playfair_Display,
} from "next/font/google";
import "./globals.css";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";
import ScrollToTop from "@/components/layout/ScrollToTop";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

// 💐 Add Fleur De Leah
const fleurDeLeah = Fleur_De_Leah({
	variable: "--font-fleur",
	subsets: ["latin"],
	weight: "400", // Only one weight available
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

// this acts as a parent for all of the other pages
export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${fleurDeLeah.variable}  antialiased`}>
				<ScrollToTop></ScrollToTop>
				<div className="flex flex-col gap-10 min-h-screen w-screen">
					{/* this is to wrap not full frame */}
					<div className="ml-4 mr-4 flex flex-col gap-2 sm:ml-20 sm:mr-20 lg:gap-7 grow">
						<Header></Header>
						{children}
					</div>
					<Footer></Footer>
				</div>
			</body>
		</html>
	);
}
